### PR TITLE
Fix launching Epic Games

### LINKED ISSUE #20: Epic Games support tracking
- although there is code to search HKEY_CLASSES_ROOT/amongus and amongus does exist, epic games's au is not being autodetected

Image

however, even if it was detected, you can not start epic by exe directly which is being done right now if i manually select it, will starting via epic protocol still let bepinex access the game?

summary i think of so far:
- fix autodetecting game folder
- automatically set bepinex x64 - #21 
- epic login ui and http request flow before running exe

### PR DESCRIPTION
**Pull request by yanpla**
Closes #20

### CODE REVIEW

File: src-tauri/src/utils/finder.rs [hunk 1]
```diff
@@ -5,12 +5,18 @@ use std::path::{Path, PathBuf};
...
+const EPIC_FOLDER: &str = ".egstore";
 
 /// Checks if the directory exists and contains the Among Us executable.
 fn verify_among_us_directory(path: &Path) -> bool {
     path.is_dir() && path.join(AMONG_US_EXE).is_file()
 }
 
+/// Checks if the directory contains Epic Games indicator (.egs folder).
+fn is_epic_installation(path: &Path) -> bool {
+    path.join(EPIC_FOLDER).is_dir()
```
Comment (whichtwix) [inline src-tauri/src/utils/finder.rs]: if people happen to downgrade and select that folder, .egstore wont be there, maybe theres smth in Among Us_Data to use
